Maze
nzinov/maze pull request #1
Opened 2016-10-08 17:08 UTC by onaga1958

2016-10-08 17:23 UTC, nzinov requested changes

2016-10-08 17:23 UTC, nzinov commented on game.py
> +#from emoji import emojize
Почему ты это закомментил?

2016-10-08 17:23 UTC, nzinov commented on game.py
> +           #game.log(game.player(), "Вы сходили {}".format(NAME[direction]))
Это лучше убрать

2016-10-08 17:23 UTC, nzinov commented on objects.py
> +class Jumping_Rope(Object):
класс должен называться JumpingRope

2016-10-08 17:23 UTC, nzinov commented on objects.py
> +            game.log("Вы попрыгали. Кажется, под Вами и правда земля")
Лучше "вы" с маленькой буквы

2016-10-08 17:23 UTC, nzinov commented on objects.py
> +            if hit == False:
if not hit :smile:

2016-10-08 17:56 UTC, onaga1958 commented on game.py
> +#from emoji import emojize
У меня почему-то не было этой библиотеки, а смайлы мне для тестов были не нужны. Забыл раскоментить.

2016-10-08 17:56 UTC, onaga1958 commented on objects.py
> +            if hit == False:
А точно, лол)

2016-10-09 08:59 UTC, nzinov commented on effects.py
> +            for eff in self.spirit.effects:
Это зачем?

2016-10-09 09:00 UTC, nzinov commented on effects.py
> +class DeferredSleep(ExpiringEffect):
Думаю, что лучше сделать отложенный эффект в общем случае, а не только для сна.

2016-10-09 12:38 UTC, onaga1958 commented on effects.py
> +            for eff in self.spirit.effects:
Если реальное тело вступило в отложенный сон еще раз, не успев уснуть, то у спирита этот второй эффект тоже появиться. Если этот второй сон триггернется, то произойдет что-то странное.

2016-10-09 12:50 UTC, nzinov commented on effects.py
> +            for eff in self.spirit.effects:
А по-моему нормально - заснет во сне и все тут

2016-10-09 12:59 UTC, onaga1958 commented on effects.py
> +            for eff in self.spirit.effects:
Но тогда новый дух создаться в том же мире. Хз, мне кажется это все же странно. Тогда можно будет духом духа убить духа и дважды проснуться, лол. Хотя, это даже прикольно

2016-10-09 13:01 UTC, nzinov commented
Да, все равно ведь это все во сне.) Ну и это сохраняет ту логику, что во
сне с тобой происходит все то, что происходило бы наяву

Николай Зинов
nzinov@gmail.com

вс, 9 окт. 2016 г. в 15:59, onaga1958 <notifications@github.com>:

> *@onaga1958* commented on this pull request.
> ------------------------------
>
> In effects.py <https://github.com/nzinov/maze/pull/1>:
>
> > @@ -69,6 +71,9 @@ def event(self, game, player, event):
>          if event == "start":
>              self.spirit = deepcopy(player)
>              self.spirit.effects.pop() #remove this effect
> +            for eff in self.spirit.effects:
>
> Но тогда новый дух создаться в том же мире. Хз, мне кажется это все же
> странно. Тогда можно будет духом духа убить духа и дважды проснуться, лол.
> Хотя, это даже прикольно
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/nzinov/maze/pull/1>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGF_lnFRSEDyRZ-K_FrzD5LwUCKVzoKvks5qyOU9gaJpZM4KRxav>
> .
>

2016-10-09 13:02 UTC, nzinov commented on effects.py
> +            for eff in self.spirit.effects:
Да, все равно ведь это все во сне.) Ну и это сохраняет ту логику, что во
сне с тобой происходит все то, что происходило бы наяву

2016-10-10 04:32 UTC, merged